/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a calculatoradaptor slavecalculator.xml
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CALCULATORADAPTOR_H
#define CALCULATORADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.blikoon.CalculatorInterface
 */
class CalculatorInterfaceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.blikoon.CalculatorInterface")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.blikoon.CalculatorInterface\">\n"
"    <signal name=\"productResult\">\n"
"      <arg direction=\"out\" type=\"d\" name=\"product\"/>\n"
"    </signal>\n"
"    <signal name=\"divisionResult\">\n"
"      <arg direction=\"out\" type=\"d\" name=\"quotient\"/>\n"
"    </signal>\n"
"    <method name=\"multiply\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"factor1\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"factor2\"/>\n"
"    </method>\n"
"    <method name=\"divide\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"divident\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"divisor\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    CalculatorInterfaceAdaptor(QObject *parent);
    virtual ~CalculatorInterfaceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    double divide(double divident, double divisor);
    double multiply(double factor1, double factor2);
Q_SIGNALS: // SIGNALS
    void divisionResult(double quotient);
    void productResult(double product);
};

#endif
